# TODO: Replace with actual hardware config generated by nixos-generate-config
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # boot.initrd.availableKernelModules = [ ... ];
  # boot.initrd.kernelModules = [ ... ];
  # boot.kernelModules = [ ... ];
  # boot.extraModulePackages = [ ];

  # fileSystems."/" = { device = ...; fsType = "ext4"; };

  # swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
